#!/usr/bin/env python3
"""
The app's words in English, Uzbek and Russian, in one table, written out as
values/, values-uz/ and values-ru/ strings.xml. Edit here, run, never edit the XML.

Usage: python3 tools/strings.py
"""
import json
import pathlib
from xml.sax.saxutils import escape

RES = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/res"

S = {  # key: (en, uz, ru)
 "app_name": ("Dawnwick", "Dawnwick", "Dawnwick"),
 "tab_today": ("Today", "Bugun", "Сегодня"),
 "tab_alarms": ("Alarms", "Budilnik", "Будильники"),
 "tab_sleep": ("Sleep", "Uyqu", "Сон"),
 "tab_play": ("Play", "O'yin", "Игры"),
 "tab_settings": ("Settings", "Sozlamalar", "Настройки"),
 "channel_ring": ("Ringing alarm", "Jiringlayotgan budilnik", "Звонящий будильник"),
 "channel_wake_check": ("Wake check", "Uyg'oqlik tekshiruvi", "Проверка пробуждения"),
 "ring_notification_body": ("Alarm · %s. Open to turn it off.", "Budilnik · %s. O'chirish uchun oching.", "Будильник · %s. Откройте, чтобы выключить."),
 "wake_check_title": ("Still awake?", "Hali uyg'oqmisiz?", "Ещё не спите?"),
 "wake_check_body": ("Confirm you're up and your alarm won't ring again.", "Turganingizni tasdiqlang, shunda budilnik qayta jiringlamaydi.", "Подтвердите, что встали, и будильник больше не зазвонит."),
 "wake_check_body_label": ("Wake check for “%s” — confirm within 2 minutes or it rings again.", "“%s” uchun tekshiruv — 2 daqiqa ichida tasdiqlang, aks holda yana jiringlaydi.", "Проверка для «%s» — подтвердите за 2 минуты, иначе будильник зазвонит снова."),
 "wake_check_awake": ("Yes, I'm awake", "Ha, uyg'oqman", "Да, я не сплю"),
 "wake_check_fell_asleep": ("I fell back asleep", "Yana uxlab qoldim", "Я снова уснул"),
 "streak_starts_today": ("Your streak starts today.", "Seriyangiz bugundan boshlanadi.", "Ваша серия начинается сегодня."),
 "new_alarm": ("New alarm", "Yangi budilnik", "Новый будильник"),
 "edit_alarm": ("Edit alarm", "Budilnikni tahrirlash", "Изменить будильник"),
 "next_alarm_in": ("Next alarm in %s", "Keyingi budilnik %s dan keyin", "Следующий будильник через %s"),
 "next_alarm": ("NEXT ALARM", "KEYINGI BUDILNIK", "СЛЕДУЮЩИЙ БУДИЛЬНИК"),
 "rings_in": ("Rings in %s", "%s dan keyin jiringlaydi", "Прозвенит через %s"),
 "rings_in_under_minute": ("< 1 min", "< 1 daqiqa", "< 1 мин"),
 "rings_in_minutes": ("%d min", "%d daqiqa", "%d мин"),
 "rings_in_hours": ("%d h", "%d soat", "%d ч"),
 "rings_in_hours_minutes": ("%1$d h %2$d min", "%1$d soat %2$d daqiqa", "%1$d ч %2$d мин"),
 "recurrence_daily": ("Every day", "Har kuni", "Каждый день"),
 "recurrence_weekdays": ("Weekdays", "Ish kunlari", "По будням"),
 "recurrence_weekends": ("Weekends", "Dam olish kunlari", "По выходным"),
 "recurrence_no_days": ("No days set", "Kunlar tanlanmagan", "Дни не выбраны"),
 "recurrence_once": ("Once · %s", "Bir marta · %s", "Однократно · %s"),
 "one_time": ("One-time", "Bir marta", "Однократно"),
 "today_only": ("Today only", "Faqat bugun", "Только сегодня"),
 "no_alarms_yet": ("No alarms yet", "Hali budilnik yo'q", "Будильников пока нет"),
 "no_alarms_detail": ("Add an alarm and choose the mission that turns it off.", "Budilnik qo'shing va uni o'chiradigan missiyani tanlang.", "Добавьте будильник и выберите задание, которое его выключит."),
 "add_first_alarm": ("Add your first alarm", "Birinchi budilnikni qo'shish", "Добавить первый будильник"),
 "no_alarm_set": ("No alarm set", "Budilnik qo'yilmagan", "Будильник не установлен"),
 "delete_alarm_question": ("Delete this alarm?", "Budilnik o'chirilsinmi?", "Удалить будильник?"),
 "delete_alarm_message": ("The %s alarm will be removed.", "%s dagi budilnik o'chiriladi.", "Будильник на %s будет удалён."),
 "delete_alarm_message_label": ("“%1$s” at %2$s will be removed.", "%2$s dagi “%1$s” o'chiriladi.", "«%1$s» на %2$s будет удалён."),
 "delete_alarm": ("Delete alarm", "Budilnikni o'chirish", "Удалить будильник"),
 "duplicate_alarm": ("Duplicate alarm", "Nusxa olish", "Дублировать будильник"),
 "delete": ("Delete", "O'chirish", "Удалить"),
 "edit": ("Edit", "Tahrirlash", "Изменить"),
 "duplicate": ("Duplicate", "Nusxa olish", "Дублировать"),
 "more": ("More", "Yana", "Ещё"),
 "cancel": ("Cancel", "Bekor qilish", "Отмена"),
 "save": ("Save", "Saqlash", "Сохранить"),
 "ok": ("OK", "OK", "OK"),
 "done": ("Done", "Tayyor", "Готово"),
 "fix": ("Fix", "Tuzatish", "Исправить"),
 "off": ("Off", "O'chiq", "Выкл."),
 "unlimited": ("Unlimited", "Cheksiz", "Без ограничений"),
 "n_min": ("%d min", "%d daqiqa", "%d мин"),
 "test": ("Test", "Sinash", "Тест"),
 "test_alarm": ("Test alarm", "Sinov budilnigi", "Тестовый будильник"),
 "test_alarm_title": ("Hear it before you trust it", "Ishonishdan oldin eshitib ko'ring", "Услышьте, прежде чем доверять"),
 "test_alarm_detail": ("A real alarm in 30 seconds, at full volume.", "30 soniyadan keyin to'liq ovozda haqiqiy budilnik.", "Настоящий будильник через 30 секунд, на полной громкости."),
 "test_alarm_scheduled": ("Your test alarm rings in 30 seconds. Lock the phone to see it on the lock screen.", "Sinov budilnigi 30 soniyadan keyin jiringlaydi. Qulf ekranida ko'rish uchun telefonni qulflang.", "Тестовый будильник зазвонит через 30 секунд. Заблокируйте телефон, чтобы увидеть его на экране блокировки."),
 "test_alarm_failed": ("The test alarm could not be scheduled. Check the reliability settings.", "Sinov budilnigini qo'yib bo'lmadi. Ishonchlilik sozlamalarini tekshiring.", "Не удалось поставить тестовый будильник. Проверьте настройки надёжности."),
 "alarm_saved_not_scheduled": ("The alarm was saved but Android would not schedule it, so it will not ring. Allow alarms in Settings.", "Budilnik saqlandi, lekin Android uni rejalashtirmadi — u jiringlamaydi. Sozlamalarda budilniklarga ruxsat bering.", "Будильник сохранён, но Android не запланировал его — он не зазвонит. Разрешите будильники в настройках."),
 "alarm_wont_ring": ("Alarm won't ring", "Budilnik jiringlamaydi", "Будильник не зазвонит"),
 "could_not_save": ("Could not save", "Saqlab bo'lmadi", "Не удалось сохранить"),
 "free_alarm_limit": ("Free covers 2 alarms. Premium has no limit.", "Bepul versiyada 2 ta budilnik. Premium'da cheklov yo'q.", "Бесплатно — 2 будильника. В Premium без ограничений."),
 "alarms_wont_ring": ("Alarms won't ring reliably", "Budilnik ishonchli jiringlamaydi", "Будильники могут не зазвонить"),
 "perm_notifications": ("Notifications", "Bildirishnomalar", "Уведомления"),
 "perm_notifications_detail": ("The ring screen comes as a notification. Turn notifications on.", "Jiringlash ekrani bildirishnoma orqali chiqadi. Bildirishnomalarni yoqing.", "Экран будильника приходит уведомлением. Включите уведомления."),
 "perm_exact": ("Alarms & reminders", "Budilnik va eslatmalar", "Будильники и напоминания"),
 "perm_exact_detail": ("Without it Android may ring late. Allow alarms & reminders.", "Busiz Android kech jiringlatishi mumkin. Budilnik va eslatmalarga ruxsat bering.", "Без этого Android может звонить с опозданием. Разрешите будильники и напоминания."),
 "perm_full_screen": ("Full-screen alarm", "To'liq ekranli budilnik", "Будильник на весь экран"),
 "perm_full_screen_detail": ("Lets the alarm open over the lock screen.", "Budilnik qulf ekrani ustida ochilishiga imkon beradi.", "Позволяет будильнику открываться поверх экрана блокировки."),
 "perm_battery": ("Battery optimisation", "Batareya tejash", "Оптимизация батареи"),
 "perm_battery_detail": ("Some phones stop apps to save battery. Set Dawnwick to “Not optimised”.", "Ba'zi telefonlar batareyani tejash uchun ilovalarni to'xtatadi. Dawnwick'ni “Optimallashtirilmagan” qilib qo'ying.", "Некоторые телефоны останавливают приложения ради экономии батареи. Отключите оптимизацию для Dawnwick."),
 "reliability": ("Reliability", "Ishonchlilik", "Надёжность"),
 "reliability_footer": ("Each of these keeps alarms on time on Android. Tap one to open its setting.", "Bularning har biri Android'da budilnik o'z vaqtida jiringlashini ta'minlaydi. Sozlamani ochish uchun bosing.", "Каждый пункт помогает будильнику звонить вовремя на Android. Нажмите, чтобы открыть настройку."),
 "alarms_section": ("Alarms", "Budilniklar", "Будильники"),
 "default_sound": ("Default sound", "Standart ovoz", "Звук по умолчанию"),
 "haptics": ("Haptics", "Tebranish", "Вибрация"),
 "about": ("About", "Ilova haqida", "О приложении"),
 "version": ("Version", "Versiya", "Версия"),
 "schedule": ("Schedule", "Jadval", "Расписание"),
 "date": ("Date", "Sana", "Дата"),
 "wake_missions": ("Wake missions", "Uyg'otish missiyalari", "Задания для пробуждения"),
 "missions_footer": ("Up to three, in this order. Tap one to change, move or remove it.", "Ko'pi bilan uchta, shu tartibda. O'zgartirish, ko'chirish yoki olib tashlash uchun bosing.", "До трёх, в этом порядке. Нажмите, чтобы изменить, переместить или удалить."),
 "add_mission": ("Add mission", "Missiya qo'shish", "Добавить задание"),
 "n_of_3": ("%d of 3", "3 tadan %d", "%d из 3"),
 "setup_needed": ("Setup needed", "Sozlash kerak", "Нужна настройка"),
 "label": ("Label", "Nom", "Название"),
 "name_this_alarm": ("Name this alarm", "Budilnikka nom bering", "Назовите будильник"),
 "sound": ("Sound", "Ovoz", "Звук"),
 "gradual_wake": ("Gradual wake", "Asta-sekin uyg'otish", "Плавное пробуждение"),
 "snooze": ("Snooze", "Kechiktirish", "Отложить"),
 "duration": ("Duration", "Davomiylik", "Длительность"),
 "max_snoozes": ("Max snoozes", "Ko'pi bilan", "Максимум"),
 "wake_check": ("Wake check", "Uyg'oqlik tekshiruvi", "Проверка пробуждения"),
 "still_awake": ("Still awake?", "Hali uyg'oqmisiz?", "Ещё не спите?"),
 "still_awake_detail": ("Rings again if you fall back asleep", "Yana uxlab qolsangiz, qayta jiringlaydi", "Зазвонит снова, если вы уснёте"),
 "discard_changes_question": ("Discard changes?", "O'zgarishlar bekor qilinsinmi?", "Отменить изменения?"),
 "discard_changes": ("Discard changes", "Bekor qilish", "Отменить изменения"),
 "keep_editing": ("Keep editing", "Davom etish", "Продолжить"),
 "hour": ("Hour", "Soat", "Часы"),
 "minute": ("Minute", "Daqiqa", "Минуты"),
 "am_pm": ("AM or PM", "AM yoki PM", "AM или PM"),
 "start_mission": ("Start mission", "Missiyani boshlash", "Начать задание"),
 "no_more_snoozes": ("No more snoozes", "Kechiktirish qolmadi", "Отложить больше нельзя"),
 "snooze_min": ("Snooze %d min", "%d daqiqaga kechiktirish", "Отложить на %d мин"),
 "snooze_min_last": ("Snooze %d min · last one", "%d daqiqaga kechiktirish · oxirgisi", "Отложить на %d мин · последний раз"),
 "snooze_min_left": ("Snooze %1$d min · %2$d left", "%1$d daqiqaga kechiktirish · %2$d ta qoldi", "Отложить на %1$d мин · осталось %2$d"),
 "snooze_failed": ("The snooze could not be set, so the alarm keeps ringing.", "Kechiktirib bo'lmadi, budilnik jiringlashda davom etadi.", "Не удалось отложить, будильник продолжает звонить."),
 "good_morning": ("Good morning.", "Xayrli tong.", "Доброе утро."),
 "good_morning_greeting": ("Good morning", "Xayrli tong", "Доброе утро"),
 "good_afternoon": ("Good afternoon", "Xayrli kun", "Добрый день"),
 "good_evening": ("Good evening", "Xayrli kech", "Добрый вечер"),
 "success_summary": ("%1$s · %2$d min", "%1$s · %2$d daqiqa", "%1$s · %2$d мин"),
 "mission_math": ("Math", "Matematika", "Математика"),
 "mission_shake": ("Shake", "Silkitish", "Встряхнуть"),
 "mission_steps": ("Steps", "Qadamlar", "Шаги"),
 "mission_qr": ("QR code", "QR kod", "QR-код"),
 "mission_memory": ("Memory", "Xotira", "Память"),
 "mission_typing": ("Typing", "Yozish", "Набор текста"),
 "mission_draw": ("Draw", "Chizish", "Рисунок"),
 "mission_jump": ("Jump", "Sakrash", "Прыжки"),
 "mission_catch_cat": ("Catch the cat", "Mushukni tut", "Поймай кота"),
 "mission_math_detail": ("Solve sums until your head is on.", "Boshingiz ishlab ketguncha misollar yeching.", "Решайте примеры, пока голова не включится."),
 "mission_shake_detail": ("Shake the phone hard, again and again.", "Telefonni qattiq, qayta-qayta silkiting.", "Сильно трясите телефон, снова и снова."),
 "mission_steps_detail": ("Get up and walk a few steps.", "Turing va bir necha qadam yuring.", "Встаньте и пройдите несколько шагов."),
 "mission_qr_detail": ("Scan a code you put in another room.", "Boshqa xonaga qo'ygan kodingizni skanerlang.", "Отсканируйте код, оставленный в другой комнате."),
 "mission_memory_detail": ("Remember the pattern and tap it back.", "Naqshni eslab qoling va qayta bosing.", "Запомните узор и повторите его."),
 "mission_typing_detail": ("Type a phrase of your own, exactly.", "O'zingiz tanlagan iborani aniq yozing.", "Наберите свою фразу без ошибок."),
 "mission_draw_detail": ("Draw the same shape you drew the night before.", "Kechqurun chizgan shaklingizni qayta chizing.", "Нарисуйте ту же фигуру, что и вечером."),
 "mission_jump_detail": ("Jump with the phone in your hand.", "Telefonni qo'lda ushlab sakrang.", "Прыгайте с телефоном в руке."),
 "mission_catch_cat_detail": ("Tap the cat before it jumps away.", "Mushuk qochib ketguncha uni bosing.", "Нажмите на кота, пока он не убежал."),
 "mission_no_accelerometer": ("This phone has no accelerometer, so %s can't be used.", "Bu telefonda akselerometr yo'q, shuning uchun %s ishlamaydi.", "В этом телефоне нет акселерометра, поэтому «%s» недоступно."),
 "mission_no_step_sensor": ("This phone can't count steps, so Steps can't be used.", "Bu telefon qadamlarni sanay olmaydi, shuning uchun Qadamlar ishlamaydi.", "Этот телефон не умеет считать шаги, поэтому «Шаги» недоступны."),
 "mission_no_camera": ("This phone has no camera, so QR code can't be used.", "Bu telefonda kamera yo'q, shuning uchun QR kod ishlamaydi.", "В этом телефоне нет камеры, поэтому «QR-код» недоступен."),
 "mission_permission_swapped": ("%s isn't allowed on this phone any more — solve Math instead.", "%s uchun ruxsat olib qo'yilgan — o'rniga Matematikani yeching.", "Для «%s» больше нет разрешения — решите математику."),
 "mission_premium_swapped": ("%s needs Premium — solve Math instead.", "%s Premium talab qiladi — o'rniga Matematikani yeching.", "Для «%s» нужен Premium — решите пример."),
 "mission_screen_reader_swapped": ("%s can't be used with TalkBack — solve Math instead.", "%s TalkBack bilan ishlamaydi — o'rniga Matematikani yeching.", "«%s» нельзя пройти с TalkBack — решите математику."),
 "steps_instruction": ("Walk to wake up!", "Uyg'onish uchun yuring!", "Идите, чтобы проснуться!"),
 "steps_unavailable": ("Step counting unavailable on this device.", "Bu qurilmada qadam sanash mavjud emas.", "Подсчёт шагов недоступен на этом устройстве."),
 "steps_denied": ("Physical activity access is off, so steps can't be counted.", "Jismoniy faollikka ruxsat yo'q, shuning uchun qadamlar sanalmaydi.", "Доступ к физической активности выключен, поэтому шаги не считаются."),
 "steps_permission_needed": ("Steps needs access to physical activity to count.", "Qadamlarni sanash uchun jismoniy faollikka ruxsat kerak.", "Для подсчёта шагов нужен доступ к физической активности."),
 "allow": ("Allow", "Ruxsat berish", "Разрешить"),
 "open_settings": ("Open Settings", "Sozlamalarni ochish", "Открыть настройки"),
 "simulate_steps": ("Simulate steps", "Qadamlarni taqlid qilish", "Имитировать шаги"),
 "simulate_jump": ("Simulate jump", "Sakrashni taqlid qilish", "Имитировать прыжок"),
 "simulate_shake": ("Simulate shake", "Silkitishni taqlid qilish", "Имитировать встряхивание"),
 "simulate_scan": ("Simulate scan", "Skanerlashni taqlid qilish", "Имитировать сканирование"),
 "jump_instruction": ("Jump to wake up!", "Uyg'onish uchun sakrang!", "Прыгайте, чтобы проснуться!"),
 "jump_unavailable": ("Jump detection unavailable on this device.", "Bu qurilmada sakrashni aniqlash mavjud emas.", "Распознавание прыжков недоступно на этом устройстве."),
 "camera_needed": ("Camera access is needed to scan codes. Turn it on in Settings.", "Kodlarni skanerlash uchun kameraga ruxsat kerak. Uni Sozlamalarda yoqing.", "Для сканирования кодов нужен доступ к камере. Включите его в настройках."),
 "qr_not_configured": ("This alarm's QR code has not been set up.", "Bu budilnik uchun QR kod sozlanmagan.", "QR-код для этого будильника не настроен."),
 "qr_instruction": ("Scan your registered QR or barcode", "Ro'yxatga olingan QR yoki shtrix-kodni skanerlang", "Отсканируйте зарегистрированный QR- или штрихкод"),
 "qr_wrong": ("Wrong code — scan your registered code", "Noto'g'ri kod — ro'yxatga olingan kodni skanerlang", "Не тот код — отсканируйте зарегистрированный"),
 "qr_setup_title": ("Register code", "Kodni ro'yxatga olish", "Регистрация кода"),
 "qr_setup_instruction": ("Scan the QR or barcode you will use at alarm time. Leave it in another room.", "Budilnik vaqtida skanerlaydigan QR yoki shtrix-kodni skanerlang. Uni boshqa xonada qoldiring.", "Отсканируйте QR- или штрихкод, который будете сканировать утром. Оставьте его в другой комнате."),
 "qr_registered": ("Code registered", "Kod ro'yxatga olindi", "Код зарегистрирован"),
 "qr_register": ("Register", "Ro'yxatga olish", "Зарегистрировать"),
 "rescan": ("Rescan", "Qayta skanerlash", "Пересканировать"),
 "draw_instruction": ("Draw your shape", "Shaklingizni chizing", "Нарисуйте свою фигуру"),
 "draw_checking": ("Checking…", "Tekshirilmoqda…", "Проверяем…"),
 "draw_wrong": ("Try again — match your saved shape", "Qayta urinib ko'ring — saqlangan shaklga o'xshating", "Ещё раз — повторите сохранённую фигуру"),
 "draw_not_calibrated": ("Not calibrated — edit this alarm to set up Draw.", "Sozlanmagan — Chizishni sozlash uchun budilnikni tahrirlang.", "Не настроено — измените будильник, чтобы настроить рисунок."),
 "draw_setup_title": ("Draw setup", "Chizishni sozlash", "Настройка рисунка"),
 "draw_setup_first": ("Draw your shape (1 of 2)", "Shaklingizni chizing (1/2)", "Нарисуйте фигуру (1 из 2)"),
 "draw_setup_second": ("Draw it again, from memory (2 of 2)", "Uni yana, yoddan chizing (2/2)", "Нарисуйте её ещё раз, по памяти (2 из 2)"),
 "draw_setup_done": ("Shape saved! This is the one to draw in the morning.", "Shakl saqlandi! Ertalab aynan shuni chizasiz.", "Фигура сохранена! Именно её нужно будет нарисовать утром."),
 "draw_setup_action": ("Set up", "Sozlash", "Настроить"),
 "draw_redraw": ("Redraw", "Qayta chizish", "Перерисовать"),
 "clear": ("Clear", "Tozalash", "Очистить"),
 "next": ("Next", "Keyingi", "Далее"),
 "setup_before_save": ("Set this mission up before saving the alarm.", "Budilnikni saqlashdan oldin bu missiyani sozlang.", "Настройте это задание, прежде чем сохранять будильник."),
 "catch_hint": ("Tap the cat before it jumps away.", "Mushuk sakrab ketguncha uni bosing.", "Нажмите на кота, пока он не отпрыгнул."),
 "cat": ("Cat", "Mushuk", "Кот"),
 "no_alarm_detail": ("Tomorrow starts when you say so.", "Ertangi kun siz aytganda boshlanadi.", "Завтра начнётся, когда вы скажете."),
 "set_an_alarm": ("Set an alarm", "Budilnik qo'yish", "Поставить будильник"),
 "day_today": ("Today", "Bugun", "Сегодня"),
 "day_tomorrow": ("Tomorrow", "Ertaga", "Завтра"),
 "cat_line_sleeping": ("Sleep well. I'll wake you.", "Yaxshi uxlang. Men uyg'otaman.", "Спокойной ночи. Я разбужу."),
 "cat_line_proud": ("Day %d of your streak.", "Seriyangizning %d-kuni.", "%d-й день вашей серии."),
 "cat_line_grumpy": ("Missed the last one. Tomorrow counts.", "Oxirgisi o'tkazib yuborildi. Ertangisi hisobga kiradi.", "Прошлый пропущен. Завтра считается."),
 "streak_title": ("Streak", "Seriya", "Серия"),
 "streak_empty": ("Complete your morning mission to start your streak.", "Seriyani boshlash uchun ertalabki missiyani bajaring.", "Выполните утреннее задание, чтобы начать серию."),
 "streak_none": ("No streak yet", "Hali seriya yo'q", "Серии пока нет"),
 "next_trick": ("Next trick at %1$d: %2$s", "Keyingi hiyla %1$d da: %2$s", "Следующий трюк на %1$d: %2$s"),
 "today_section": ("Today", "Bugun", "Сегодня"),
 "calendar_offer": ("Your first event of the day", "Kunning birinchi tadbiri", "Первое событие дня"),
 "calendar_connect": ("Connect", "Ulash", "Подключить"),
 "weather_offer": ("The weather where you are", "Siz turgan joydagi ob-havo", "Погода там, где вы"),
 "weather_add": ("Add weather", "Ob-havoni qo'shish", "Добавить погоду"),
 "weather_location_off": ("Weather needs location, which is off", "Ob-havo uchun joylashuv kerak, u o'chirilgan", "Для погоды нужна геолокация, она выключена"),
 "weather_no_location": ("Couldn't find where you are", "Joylashuvingizni aniqlab bo'lmadi", "Не удалось определить, где вы"),
 "weather_unavailable": ("Weather unavailable right now", "Ob-havo hozircha mavjud emas", "Погода сейчас недоступна"),
 "turn_on": ("Turn on", "Yoqish", "Включить"),
 "high_low": ("H:%1$d° L:%2$d°", "Y:%1$d° P:%2$d°", "Макс.:%1$d° мин.:%2$d°"),
 "focus_title": ("Focus", "Diqqat", "Фокус"),
 "focus_placeholder": ("What matters most today?", "Bugun eng muhimi nima?", "Что сегодня важнее всего?"),
 "back": ("Back", "Orqaga", "Назад"),
 "weather_title": ("Weather", "Ob-havo", "Погода"),
 "your_location": ("Your location", "Sizning joylashuvingiz", "Ваше местоположение"),
 "weather_updated": ("Updated %s", "%s da yangilandi", "Обновлено в %s"),
 "wind": ("Wind", "Shamol", "Ветер"),
 "humidity": ("Humidity", "Namlik", "Влажность"),
 "precipitation": ("Precipitation", "Yog'ingarchilik", "Осадки"),
 "wind_kmh": ("%d km/h", "%d km/soat", "%d км/ч"),
 "wind_mph": ("%d mph", "%d mil/soat", "%d миль/ч"),
 "open_meteo_credit": ("Weather data by Open-Meteo.com", "Ob-havo ma'lumotlari: Open-Meteo.com", "Данные о погоде: Open-Meteo.com"),
 "wx_clear": ("Clear", "Ochiq", "Ясно"),
 "wx_mostly_clear": ("Mostly clear", "Asosan ochiq", "Преимущественно ясно"),
 "wx_partly_cloudy": ("Partly cloudy", "Qisman bulutli", "Переменная облачность"),
 "wx_cloudy": ("Cloudy", "Bulutli", "Облачно"),
 "wx_fog": ("Foggy", "Tumanli", "Туман"),
 "wx_drizzle": ("Drizzle", "Mayda yomg'ir", "Морось"),
 "wx_freezing_drizzle": ("Freezing drizzle", "Muzlovchi mayda yomg'ir", "Ледяная морось"),
 "wx_rain": ("Rain", "Yomg'ir", "Дождь"),
 "wx_heavy_rain": ("Heavy rain", "Kuchli yomg'ir", "Сильный дождь"),
 "wx_freezing_rain": ("Freezing rain", "Muzlovchi yomg'ir", "Ледяной дождь"),
 "wx_snow": ("Snow", "Qor", "Снег"),
 "wx_heavy_snow": ("Heavy snow", "Kuchli qor", "Сильный снег"),
 "wx_snow_grains": ("Snow grains", "Qor donalari", "Снежные зёрна"),
 "wx_showers": ("Rain showers", "Jala", "Ливень"),
 "wx_heavy_showers": ("Heavy showers", "Kuchli jala", "Сильный ливень"),
 "wx_snow_showers": ("Snow showers", "Qor bo'roni", "Снегопад"),
 "wx_thunder": ("Thunderstorms", "Momaqaldiroq", "Гроза"),
 "wx_thunder_hail": ("Thunderstorms with hail", "Do'lli momaqaldiroq", "Гроза с градом"),
 "wx_unknown": ("Unknown", "Noma'lum", "Неизвестно"),
 "best_streak": ("Best %d", "Eng yaxshi: %d", "Лучшая: %d"),
 "mornings_this_month": ("%d this month", "bu oy %d", "%d в этом месяце"),
 "tricks_title": ("The cat's tricks", "Mushukning hiylalari", "Трюки кота"),
 "tricks_detail": ("A streak teaches the cat a trick at 3, 7, 14, 30, 60 and 100 mornings. It keeps them, whatever happens to the streak.", "Seriya mushukka 3, 7, 14, 30, 60 va 100 tongda hiyla o'rgatadi. Seriya uzilsa ham ular qoladi.", "Серия учит кота трюку на 3, 7, 14, 30, 60 и 100 утрах. Они остаются, что бы ни случилось с серией."),
 "trick_wave": ("Wave", "Qo'l silkitish", "Помахать"),
 "trick_somersault": ("Somersault", "Ag'darilish", "Сальто"),
 "trick_leap": ("Big leap", "Katta sakrash", "Большой прыжок"),
 "trick_sparkle": ("Sparkles", "Uchqunlar", "Искры"),
 "trick_collar": ("Collar and bell", "Bo'yinbog' va qo'ng'iroqcha", "Ошейник с колокольчиком"),
 "trick_medal": ("Gold medal", "Oltin medal", "Золотая медаль"),
 "trick_wave_detail": ("Tap the cat and it waves back.", "Mushukni bosing — u qo'l silkitadi.", "Нажмите на кота — он помашет."),
 "trick_somersault_detail": ("Every fourth tap, a somersault.", "Har to'rtinchi bosishda ag'dariladi.", "Каждое четвёртое нажатие — сальто."),
 "trick_leap_detail": ("Every third tap, a jump twice as high.", "Har uchinchi bosishda ikki barobar baland sakraydi.", "Каждое третье нажатие — прыжок вдвое выше."),
 "trick_sparkle_detail": ("Every tap leaves a few sparkles.", "Har bosishda uchqunlar chiqadi.", "Каждое нажатие оставляет искры."),
 "trick_collar_detail": ("A collar with a yolk bell, everywhere the cat goes.", "Mushuk qayerga borsa, sariq qo'ng'iroqli bo'yinbog' bilan.", "Ошейник с жёлтым колокольчиком, куда бы кот ни пошёл."),
 "trick_medal_detail": ("A gold medal on its collar, for a hundred mornings.", "Yuz tong uchun bo'yinbog'ida oltin medal.", "Золотая медаль на ошейнике — за сто утр."),
 "trick_progress": ("%1$d of %2$d mornings in a row", "Ketma-ket %2$d tongdan %1$d", "%1$d из %2$d утр подряд"),
 "trick_at": ("At %d mornings in a row", "Ketma-ket %d tongda", "На %d утрах подряд"),
 "learned": ("Learned", "O'rganildi", "Выучен"),
 "covers_title": ("Covers", "Himoyalar", "Подстраховки"),
 "covers_detail": ("One for every 7 mornings in a row, up to 2. A missed morning uses one, and your streak goes on.", "Ketma-ket har 7 tong uchun bittadan, ko'pi bilan 2 ta. O'tkazib yuborilgan tong bittasini ishlatadi va seriya davom etadi.", "Одна за каждые 7 утр подряд, до 2. Пропущенное утро тратит одну, и серия продолжается."),
 "covers_ready_title": ("The cat has your back", "Mushuk sizni qo'llab-quvvatlaydi", "Кот вас прикроет"),
 "covers_none": ("No covers yet", "Hali himoya yo'q", "Подстраховок пока нет"),
 "covers_ready": ("%1$d of %2$d ready", "%2$d tadan %1$d tayyor", "Готово %1$d из %2$d"),
 "won_of_scheduled": ("%1$d / %2$d scheduled", "%1$d / %2$d rejalashtirilgan", "%1$d / %2$d запланировано"),
 "legend_won": ("Woke up", "Uyg'ondi", "Проснулся"),
 "legend_covered": ("Covered", "Himoyalandi", "Прикрыто"),
 "legend_missed": ("Missed", "O'tkazildi", "Пропущено"),
 "legend_rest": ("Rest", "Dam", "Отдых"),
 "share_streak": ("Share your streak", "Seriyani ulashish", "Поделиться серией"),
 "share_streak_title": ("My morning streak", "Mening ertalabki seriyam", "Моя утренняя серия"),
 "next_cover_at": ("Next at %d in a row", "Keyingisi ketma-ket %d da", "Следующая на %d подряд"),
 "appearance": ("Appearance", "Ko'rinish", "Оформление"),
 "theme": ("Theme", "Mavzu", "Тема"),
 "appearance_system": ("System", "Tizim", "Системная"),
 "appearance_light": ("Light", "Yorug'", "Светлая"),
 "appearance_dark": ("Dark", "Qorong'i", "Тёмная"),
 "rate_app": ("Rate Dawnwick", "Dawnwick'ni baholash", "Оценить Dawnwick"),
 "help_contact": ("Help and Contact", "Yordam va aloqa", "Помощь и связь"),
 "privacy_policy": ("Privacy Policy", "Maxfiylik siyosati", "Политика конфиденциальности"),
 "missions_title": ("Missions", "Missiyalar", "Задания"),
 "picker_hint": ("Tap to add · hold to try · up to %d", "Qo'shish uchun bosing · sinash uchun ushlab turing · ko'pi bilan %d", "Нажмите, чтобы добавить · удерживайте, чтобы попробовать · до %d"),
 "picker_none": ("Pick at least one mission", "Kamida bitta missiya tanlang", "Выберите хотя бы одно задание"),
 "picker_selected": ("Selected: %s", "Tanlangan: %s", "Выбрано: %s"),
 "close_preview": ("Close preview", "Ko'rishni yopish", "Закрыть пробу"),
 "picker_math": ("Solve sums", "Misol yechish", "Решить примеры"),
 "picker_shake": ("Shake the phone", "Telefonni silkitish", "Потрясти телефон"),
 "picker_steps": ("Walk around", "Yurib chiqish", "Пройтись"),
 "picker_qr": ("Scan a code", "Kodni skanerlash", "Отсканировать код"),
 "picker_memory": ("Repeat a pattern", "Naqshni takrorlash", "Повторить узор"),
 "picker_typing": ("Type a phrase", "Ibora yozish", "Набрать фразу"),
 "picker_draw": ("Trace a shape", "Shakl chizish", "Нарисовать фигуру"),
 "picker_jump": ("Jump on the spot", "Joyida sakrash", "Попрыгать на месте"),
 "picker_catch": ("Tap it before it jumps", "Sakrashidan oldin bosing", "Нажмите, пока не прыгнул"),
 "try_mission": ("Try this mission", "Missiyani sinab ko'rish", "Попробовать задание"),
 "channel_sleep": ("Sleep tracking", "Uyqu kuzatuvi", "Отслеживание сна"),
 "channel_bedtime": ("Bedtime reminder", "Yotish eslatmasi", "Напоминание о сне"),
 "sleep_tracking_title": ("Tracking your sleep", "Uyqungiz kuzatilmoqda", "Отслеживаем ваш сон"),
 "sleep_tracking_body": ("Open Dawnwick to stop when you wake.", "Uyg'onganda to'xtatish uchun Dawnwick'ni oching.", "Откройте Dawnwick, чтобы остановить, когда проснётесь."),
 "bedtime_title": ("Time to wind down", "Uxlashga tayyorlanish vaqti", "Пора готовиться ко сну"),
 "bedtime_body": ("Your alarm is set for %s.", "Budilnik %s ga qo'yilgan.", "Будильник установлен на %s."),
 "bedtime_body_no_alarm": ("Get a good night's sleep.", "Yaxshi dam oling.", "Хорошего сна."),
 "duration_hm": ("%1$dh %2$dm", "%1$d s %2$d daq", "%1$d ч %2$d мин"),
 "sound_none": ("No sound", "Ovozsiz", "Без звука"),
 "sound_white": ("White noise", "Oq shovqin", "Белый шум"),
 "sound_brown": ("Brown noise", "Qo'ng'ir shovqin", "Коричневый шум"),
 "sleep_history_button": ("History", "Tarix", "История"),
 "sleep_tonight": ("Tonight", "Bugun kechasi", "Сегодня ночью"),
 "sleep_alarm_at": ("Alarm at %s.", "Budilnik %s da.", "Будильник в %s."),
 "sleep_alarm_at_for": ("Alarm at %1$s. Sleep now for %2$s.", "Budilnik %1$s da. Hozir yotsangiz — %2$s uyqu.", "Будильник в %1$s. Если лечь сейчас — %2$s сна."),
 "sleep_alarm_at_short": ("Alarm at %s", "Budilnik %s da", "Будильник в %s"),
 "sleep_start": ("Start sleep tracking", "Uyquni kuzatishni boshlash", "Начать отслеживание сна"),
 "sleep_wind_down_first": ("Wind down first", "Avval tinchlanish", "Сначала успокоиться"),
 "sleep_sound": ("Sleep sound", "Uyqu ovozi", "Звук для сна"),
 "sleep_monitor_noise": ("Monitor noise", "Shovqinni o'lchash", "Следить за шумом"),
 "sleep_mic_denied": ("Microphone access denied", "Mikrofonga ruxsat yo'q", "Нет доступа к микрофону"),
 "bedtime_reminder": ("Bedtime reminder", "Yotish eslatmasi", "Напоминание о сне"),
 "bedtime_remind_at": ("Remind me at", "Eslatish vaqti", "Напомнить в"),
 "bedtime_needs_permission": ("Notifications are off, so the reminder can't arrive.", "Bildirishnomalar o'chiq, eslatma kelmaydi.", "Уведомления выключены, напоминание не придёт."),
 "sleep_last_night": ("Last night", "O'tgan tun", "Прошлая ночь"),
 "health_connect_title": ("Connect Health Connect for sleep", "Uyqu uchun Health Connect'ni ulang", "Подключите Health Connect для сна"),
 "health_connect_detail": ("Dawnwick reads the sleep your phone or watch already records. Nothing leaves your device.", "Dawnwick telefon yoki soatingiz yozgan uyquni o'qiydi. Hech narsa qurilmadan chiqmaydi.", "Dawnwick читает сон, который уже записывают телефон или часы. Ничего не покидает устройство."),
 "health_connect_button": ("Connect Health Connect", "Health Connect'ni ulash", "Подключить Health Connect"),
 "sleep_no_data": ("No sleep data yet", "Hali uyqu ma'lumoti yo'q", "Данных о сне пока нет"),
 "sleep_no_data_hint": ("Track tonight to see your sleep here.", "Uyquni bu yerda ko'rish uchun bugun kechasi kuzating.", "Отследите сон сегодня ночью, чтобы увидеть его здесь."),
 "sleep_none_recorded": ("No sleep recorded", "Uyqu yozilmagan", "Сон не записан"),
 "sleep_restored": ("Session restored", "Seans tiklandi", "Сеанс восстановлен"),
 "sleep_tracking_label": ("Tracking your sleep", "Uyqungiz kuzatilmoqda", "Отслеживаем ваш сон"),
 "sleep_went_to_bed": ("Went to bed", "Yotgan vaqt", "Легли спать"),
 "sleep_alarm": ("Alarm", "Budilnik", "Будильник"),
 "sleep_asleep_for": ("Asleep for", "Uyqu davomiyligi", "Спите уже"),
 "sleep_ambient_noise": ("Ambient noise", "Atrofdagi shovqin", "Окружающий шум"),
 "sleep_quiet": ("Quiet", "Tinch", "Тихо"),
 "sleep_no_sound": ("No sound", "Ovozsiz", "Без звука"),
 "sleep_stop": ("Stop tracking", "Kuzatishni to'xtatish", "Остановить отслеживание"),
 "sleep_stop_question": ("End sleep tracking?", "Uyqu kuzatuvi tugatilsinmi?", "Завершить отслеживание сна?"),
 "sleep_stop_message": ("Your session will be saved.", "Seansingiz saqlanadi.", "Сеанс будет сохранён."),
 "sleep_keep": ("Keep tracking", "Davom ettirish", "Продолжить"),
 "sleep_recorded": ("Sleep recorded", "Uyqu yozildi", "Сон записан"),
 "sleep_total": ("Total sleep", "Jami uyqu", "Всего сна"),
 "sleep_fell_asleep": ("Fell asleep", "Uxlagan vaqt", "Уснули"),
 "sleep_woke_up": ("Woke up", "Uyg'ongan vaqt", "Проснулись"),
 "noise_loud": ("Loud", "Baland", "Громко"),
 "noise_moderate": ("Moderate", "O'rtacha", "Умеренно"),
 "noise_soft": ("Soft", "Past", "Тихо"),
 "sleep_history_title": ("Sleep history", "Uyqu tarixi", "История сна"),
 "sleep_history_empty": ("No sleep history yet", "Hali uyqu tarixi yo'q", "Истории сна пока нет"),
 "sleep_history_empty_detail": ("Track your first night or connect Health Connect to see your history here.", "Tarixni ko'rish uchun birinchi tunni kuzating yoki Health Connect'ni ulang.", "Отследите первую ночь или подключите Health Connect, чтобы увидеть историю."),
 "eight_hours": ("8h", "8 s", "8 ч"),
 "sleep_average": ("Average", "O'rtacha", "В среднем"),
 "sleep_per_night": ("Per night", "Har tunda", "За ночь"),
 "sleep_recent_nights": ("Recent nights", "So'nggi tunlar", "Последние ночи"),
 "sleep_source_tracked": ("Tracked", "Kuzatilgan", "Отслежено"),
 "sleep_source_health": ("Health Connect", "Health Connect", "Health Connect"),
 "close": ("Close", "Yopish", "Закрыть"),
 "wind_down_title": ("Wind down", "Tinchlanish", "Успокоиться"),
 "wind_down_detail": ("Breathe with the cat for a few minutes: in for four, out for six. A soft tap marks each turn, so you can close your eyes.", "Bir necha daqiqa mushuk bilan nafas oling: to'rt soniya ichga, olti soniya tashqariga. Har burilishda yengil titrash bo'ladi, ko'zingizni yumishingiz mumkin.", "Подышите с котом несколько минут: вдох на четыре, выдох на шесть. Лёгкий толчок отмечает каждую смену — можно закрыть глаза."),
 "wind_down_length": ("Length", "Davomiylik", "Длительность"),
 "minutes_short": ("%d min", "%d daq", "%d мин"),
 "wind_down_sound": ("Sound", "Ovoz", "Звук"),
 "wind_down_mind": ("On your mind?", "Xayolingizda nima bor?", "О чём думаете?"),
 "wind_down_mind_hint": ("Write it down. It waits for you on Today in the morning.", "Yozib qo'ying. Ertalab Bugun sahifasida sizni kutadi.", "Запишите. Утром это будет ждать вас на «Сегодня»."),
 "wind_down_begin": ("Begin", "Boshlash", "Начать"),
 "sleep_well": ("Sleep well.", "Yaxshi uxlang.", "Спокойной ночи."),
 "wind_down_note_waiting": ("Your note is waiting on Today.", "Yozuvingiz Bugun sahifasida kutmoqda.", "Ваша заметка ждёт на «Сегодня»."),
 "wind_down_tracking_on": ("Tracking is on. Put the phone face down.", "Kuzatuv yoqilgan. Telefonni yuzi bilan pastga qo'ying.", "Отслеживание включено. Положите телефон экраном вниз."),
 "wind_down_start_then": ("Start tracking, then put the phone face down.", "Kuzatuvni boshlang, so'ng telefonni yuzi bilan pastga qo'ying.", "Начните отслеживание, затем положите телефон экраном вниз."),
 "breathe_in": ("Breathe in", "Nafas oling", "Вдох"),
 "breathe_out": ("Breathe out", "Nafas chiqaring", "Выдох"),
 "wind_down_end": ("End", "Tugatish", "Закончить"),
 "slept": ("Slept %s", "Uxlandi: %s", "Сон: %s"),
 "rest_days_note": ("Rest days don't break your streak.", "Dam olish kunlari seriyani uzmaydi.", "Дни отдыха не прерывают серию."),
 "mission_needs_setup_swapped": ("A mission was not set up, so it is Math instead.", "Missiya sozlanmagan edi, shuning uchun o'rniga Matematika.", "Задание не было настроено, поэтому вместо него математика."),
 "math_wrong": ("Not quite. Try again.", "Noto'g'ri. Yana urinib ko'ring.", "Не совсем. Попробуйте ещё раз."),
 "math_round": ("Round %1$d of %2$d", "%2$d tadan %1$d-raund", "Раунд %1$d из %2$d"),
 "submit_answer": ("Submit answer", "Javobni yuborish", "Отправить ответ"),
 "typing_instruction": ("Type this phrase:", "Shu iborani yozing:", "Наберите фразу:"),
 "typing_wrong": ("Not quite. Check each letter.", "Noto'g'ri. Har bir harfni tekshiring.", "Не совсем. Проверьте каждую букву."),
 "typing_no_phrase": ("No phrase set", "Ibora yozilmagan", "Фраза не задана"),
 "typing_phrase": ("Phrase", "Ibora", "Фраза"),
 "typing_phrase_hint": ("At least %d letters", "Kamida %d ta harf", "Не меньше %d символов"),
 "memory_memorize": ("Memorise the pattern", "Naqshni eslab qoling", "Запомните узор"),
 "memory_recall": ("Tap the cells that lit up", "Yongan kataklarni bosing", "Нажмите на подсвеченные клетки"),
 "memory_wrong": ("Wrong — try again", "Noto'g'ri — yana urinib ko'ring", "Неверно — попробуйте ещё"),
 "memory_correct": ("Correct!", "To'g'ri!", "Верно!"),
 "cell_position": ("Row %1$d, column %2$d", "%1$d-qator, %2$d-ustun", "Строка %1$d, столбец %2$d"),
 "shake_instruction": ("Shake your phone to wake up!", "Uyg'onish uchun telefonni silkiting!", "Встряхните телефон, чтобы проснуться!"),
 "difficulty_label": ("Difficulty", "Qiyinlik", "Сложность"),
 "rounds_label": ("Rounds", "Raundlar", "Раунды"),
 "shakes_label": ("Shakes", "Silkitishlar", "Встряхивания"),
 "steps_label": ("Steps", "Qadamlar", "Шаги"),
 "jumps_label": ("Jumps", "Sakrashlar", "Прыжки"),
 "catches_label": ("Catches", "Tutishlar", "Поимки"),
 "catches_n": ("Catches: %d", "Tutish: %d", "Поимок: %d"),
 "move_earlier": ("Earlier", "Oldinga", "Раньше"),
 "move_later": ("Later", "Keyinga", "Позже"),
 "remove": ("Remove", "Olib tashlash", "Удалить"),
 "not_configured": ("Not configured", "Sozlanmagan", "Не настроено"),
 "ready": ("Ready", "Tayyor", "Готово"),
 "not_calibrated": ("Not calibrated", "Chizilmagan", "Не задано"),
 "calibrated": ("Calibrated", "Chizilgan", "Задано"),
 "coming_soon": ("Coming soon", "Tez orada", "Скоро"),
 # Games
 "game_catch": ("Catch the cat", "Mushukni tut", "Поймай кота"),
 "game_laser": ("Laser", "Lazer", "Лазер"),
 "game_boxes": ("Which box?", "Qaysi qutida?", "В какой коробке?"),
 "game_naps": ("Cat Naps", "Mushuk uyqusi", "Кошачий сон"),
 "skill_catch": ("Quick hands", "Chaqqon qo'llar", "Быстрые руки"),
 "skill_laser": ("A steady finger", "Barqaror barmoq", "Твёрдый палец"),
 "skill_boxes": ("Sharp eyes", "O'tkir ko'z", "Зоркий глаз"),
 "skill_naps": ("A clear head", "Tiniq bosh", "Ясная голова"),
 "detail_catch": ("Thirty seconds to wake your hands up.", "Qo'llaringizni uyg'otish uchun o'ttiz soniya.", "Тридцать секунд, чтобы разбудить руки."),
 "detail_catch_best": ("Best %d. Thirty seconds to wake your hands up.", "Rekord: %d. Qo'llaringizni uyg'otish uchun o'ttiz soniya.", "Рекорд: %d. Тридцать секунд, чтобы разбудить руки."),
 "detail_laser": ("Keep the dot out from under its paws.", "Nuqtani panjalari ostidan olib qoching.", "Уводите точку из-под его лап."),
 "detail_laser_best": ("Best %d. Keep the dot out from under its paws.", "Rekord: %d. Nuqtani panjalari ostidan olib qoching.", "Рекорд: %d. Уводите точку из-под его лап."),
 "detail_boxes": ("Keep your eye on the cat.", "Mushukdan ko'z uzmang.", "Не спускайте глаз с кота."),
 "detail_boxes_best": ("Best %d. Keep your eye on the cat.", "Rekord: %d. Mushukdan ko'z uzmang.", "Рекорд: %d. Не спускайте глаз с кота."),
 "detail_naps": ("Easy, medium and hard, new every morning.", "Oson, o'rtacha va qiyin — har tong yangisi.", "Лёгкая, средняя и сложная — каждое утро новые."),
 "detail_naps_streak": ("Streak %d. Today's puzzles are waiting.", "Seriya: %d. Bugungi boshqotirmalar kutyapti.", "Серия: %d. Сегодняшние головоломки ждут."),
 "detail_naps_solved": ("%1$s solved in %2$s. New ones tomorrow.", "%1$s: %2$s da yechildi. Ertaga yangilari.", "%1$s: решено за %2$s. Завтра новые."),
 "play_intro": ("Short games for the first minutes of the day: one for the hands, one for the fingers, one for the eyes, and a puzzle for the head.", "Kunning ilk daqiqalari uchun qisqa o'yinlar: qo'llar, barmoqlar va ko'zlar uchun bittadan, bosh uchun esa boshqotirma.", "Короткие игры для первых минут дня: для рук, для пальцев, для глаз и головоломка для головы."),
 "todays_game": ("Today's game", "Bugungi o'yin", "Игра дня"),
 "all_games": ("All games", "Barcha o'yinlar", "Все игры"),
 "game_play": ("Play", "O'ynash", "Играть"),
 "game_play_again": ("Play again", "Yana o'ynash", "Ещё раз"),
 "game_best": ("Best %d", "Rekord: %d", "Рекорд: %d"),
 "game_new_best": ("New best!", "Yangi rekord!", "Новый рекорд!"),
 "game_time_up": ("Time!", "Vaqt tugadi!", "Время!"),
 "game_over": ("Game over", "O'yin tugadi", "Игра окончена"),
 "game_longest_run": ("Longest run %d", "Eng uzun seriya: %d", "Лучшая серия: %d"),
 "game_in_a_row": ("%d in a row", "Ketma-ket %d", "%d подряд"),
 "game_score": ("Score %d", "Hisob: %d", "Счёт: %d"),
 "game_seconds_left": ("%d seconds left", "%d soniya qoldi", "Осталось секунд: %d"),
 "catch_rules": ("Tap the cat before it jumps away. Thirty seconds, and it gets quicker with every catch. Five in a row and each catch counts double.", "Mushuk sakrab ketmasidan uni bosing. O'ttiz soniya, har tutganingizda u tezlashadi. Ketma-ket beshta tutsangiz, har biri ikki baravar hisoblanadi.", "Нажмите на кота, пока он не отпрыгнул. Тридцать секунд, и с каждой поимкой он быстрее. Пять подряд — и каждая поимка считается вдвойне."),
 "catch_combo": ("Combo · every catch ×2", "Kombo · har tutish ×2", "Комбо · каждая поимка ×2"),
 "catch_hint": ("Tap the cat", "Mushukni bosing", "Нажмите на кота"),
 "laser_rules": ("Your finger is the dot. When the cat crouches, it is about to pounce: get out from under its paws. Every pounce you dodge is a point, and after three in a row each one counts double.", "Barmog'ingiz — lazer nuqtasi. Mushuk cho'kkalasa, hozir sakraydi: panjalari ostidan qoching. Har qochilgan sakrash — bir ochko, ketma-ket uchtadan keyin har biri ikki baravar.", "Ваш палец — это точка. Когда кот припадает к земле, он вот-вот прыгнет: уходите из-под лап. Каждый увернутый прыжок — очко, а после трёх подряд каждый считается вдвойне."),
 "laser_put_finger": ("Put a finger down", "Barmog'ingizni qo'ying", "Коснитесь экрана"),
 "laser_got_it": ("Got it", "Tutib oldi", "Поймал"),
 "laser_combo": ("Combo · every dodge ×2", "Kombo · har qochish ×2", "Комбо · каждый уворот ×2"),
 "laser_hint": ("Dodge the pounce", "Sakrashdan qoching", "Увернитесь от прыжка"),
 "boxes_rules": ("The cat hides in a box, and the boxes change places. Keep your eye on it, then tap the box it is in. It gets quicker with every find. Three wrong boxes and the game is over.", "Mushuk qutiga yashirinadi, qutilar esa joy almashadi. Ko'zingizni uzmang, keyin u turgan qutini bosing. Har topganingizda tezlashadi. Uch marta adashsangiz, o'yin tugaydi.", "Кот прячется в коробку, а коробки меняются местами. Следите за ним, затем нажмите на нужную коробку. С каждой находкой быстрее. Три ошибки — и игра окончена."),
 "boxes_watch": ("Watch the box with the cat", "Mushukli qutini kuzating", "Следите за коробкой с котом"),
 "boxes_keep_eye": ("Keep your eye on it", "Ko'z uzmang", "Не упускайте из виду"),
 "boxes_found": ("Found it!", "Topdingiz!", "Нашли!"),
 "boxes_wrong": ("Not that one", "Bu emas", "Не та"),
 "boxes_tries_left": ("%d tries left", "%d ta urinish qoldi", "Осталось попыток: %d"),
 "boxes_box": ("Box %d", "%d-quti", "Коробка %d"),
 "naps_rules": ("Every cushion wants one cat asleep on it. One cat to a row, one to a column, and no two touching, not even at a corner. Tap once to rule a cell out, twice for a cat.", "Har bir yostiqchada bitta mushuk uxlashi kerak. Har qatorda bitta, har ustunda bitta, va hech qaysi ikkitasi bir-biriga tegmasin — hatto burchakdan ham. Bir bosish — katakni chiqarib tashlash, ikki bosish — mushuk.", "На каждой подушке должен спать один кот. По одному в строке и в столбце, и никакие два не соприкасаются, даже углами. Одно касание — исключить клетку, два — кот."),
 "naps_unlimited_eyebrow": ("Unlimited · a new board every time", "Cheksiz · har safar yangi taxta", "Безлимит · каждый раз новое поле"),
 "naps_puzzle_line": ("No. %1$d · %2$s", "№ %1$d · %2$s", "№ %1$d · %2$s"),
 "naps_board_line": ("No. %1$d · %2$s · %3$d × %3$d", "№ %1$d · %2$s · %3$d × %3$d", "№ %1$d · %2$s · %3$d × %3$d"),
 "naps_unlimited_line": ("Unlimited · %1$s · %2$d × %2$d", "Cheksiz · %1$s · %2$d × %2$d", "Безлимит · %1$s · %2$d × %2$d"),
 "naps_free_tries": ("Free tries left: %d", "Bepul urinishlar: %d", "Бесплатных попыток: %d"),
 "naps_best_solved": ("Best %1$s · %2$d solved", "Rekord %1$s · %2$d ta yechildi", "Рекорд %1$s · решено: %2$d"),
 "naps_solved_in": ("Solved in %s", "%s da yechildi", "Решено за %s"),
 "naps_streak": ("Streak %d", "Seriya: %d", "Серия: %d"),
 "naps_carry_on": ("Carry on", "Davom etish", "Продолжить"),
 "naps_unlimited": ("Unlimited", "Cheksiz", "Безлимит"),
 "naps_n_free": ("%d free", "%d bepul", "%d бесплатно"),
 "naps_today": ("Today's puzzles", "Bugungi boshqotirmalar", "Сегодняшние"),
 "naps_past": ("Past puzzles", "O'tgan kunlar", "Прошлые дни"),
 "naps_no_past": ("No past puzzles yet", "Hali o'tgan boshqotirmalar yo'q", "Прошлых головоломок пока нет"),
 "naps_past_number": ("No. %d", "№ %d", "№ %d"),
 "naps_hint": ("Hint", "Maslahat", "Подсказка"),
 "naps_undo": ("Undo", "Ortga qaytarish", "Отменить"),
 "naps_all_asleep": ("All asleep.", "Hammasi uxladi.", "Все спят."),
 "naps_too_close": ("Too close. They woke each other up.", "Juda yaqin. Bir-birini uyg'otib yubordi.", "Слишком близко. Они разбудили друг друга."),
 "naps_tip": ("Tip: start with the smallest cushion.", "Maslahat: eng kichik yostiqchadan boshlang.", "Совет: начните с самой маленькой подушки."),
 "naps_count": ("%1$d of %2$d cats asleep", "%2$d tadan %1$d ta mushuk uxlayapti", "Спят %1$d из %2$d котов"),
 "naps_no_hints": ("No hints", "Maslahatsiz", "Без подсказок"),
 "naps_n_solved": ("%d solved", "%d ta yechildi", "Решено: %d"),
 "naps_next": ("Next puzzle", "Keyingi boshqotirma", "Следующая"),
 "naps_try_level": ("Try %1$s: %2$d × %2$d", "%1$s: %2$d × %2$d ni sinang", "Попробуйте «%1$s»: %2$d × %2$d"),
 "naps_another": ("Another puzzle", "Yana bitta boshqotirma", "Ещё головоломку"),
 "naps_share": ("Share", "Ulashish", "Поделиться"),
 "naps_share_text": ("Cat Naps #%1$d · %2$s · %3$s", "Mushuk uyqusi #%1$d · %2$s · %3$s", "Кошачий сон #%1$d · %2$s · %3$s"),
 "naps_free_note": ("Try unlimited puzzles free, then go Premium for a new board every time.", "Cheksiz boshqotirmalarni bepul sinab ko'ring, Premium bilan esa har safar yangi taxta.", "Попробуйте безлимит бесплатно, а с Premium — новое поле каждый раз."),
 "naps_premium_note": ("Premium: a new board every time, every past day, and hints.", "Premium: har safar yangi taxta, barcha o'tgan kunlar va maslahatlar.", "Premium: новое поле каждый раз, все прошлые дни и подсказки."),
 "premium_soon": ("Premium arrives with the next update.", "Premium keyingi yangilanishda qo'shiladi.", "Premium появится в следующем обновлении."),
 "onb_tagline": ("Sleep peacefully.\nWake confidently.", "Tinch uxlang.\nIshonch bilan uyg'oning.", "Спокойно засыпайте.\nУверенно просыпайтесь."),
 "onb_subtitle": ("Dawnwick rings even when your phone is silent, then asks you to do one small thing before it stops.", "Dawnwick telefon ovozsiz bo'lsa ham jiringlaydi va to'xtashidan oldin bitta kichik ish so'raydi.", "Dawnwick звонит даже на беззвучном и просит сделать одно маленькое дело, прежде чем замолчать."),
 "onb_point_alarm": ("A real alarm, not just a notification", "Oddiy bildirishnoma emas, haqiqiy budilnik", "Настоящий будильник, а не просто уведомление"),
 "onb_point_missions": ("Missions that make sure you're actually up", "Rostdan turganingizni tekshiradigan missiyalar", "Задания, которые проверяют, что вы встали"),
 "onb_point_sleep": ("Your sleep, tracked without wearing anything", "Hech narsa taqmasdan uyqu kuzatuvi", "Сон под контролем без браслета"),
 "onb_permissions_title": ("Alarms that actually ring", "Haqiqatan jiringlaydigan budilnik", "Будильник, который точно зазвонит"),
 "onb_permissions_subtitle": ("Android needs your say-so for these. Tap each one to open its setting.", "Android bular uchun ruxsatingizni so'raydi. Sozlamani ochish uchun bosing.", "Android просит вашего согласия. Нажмите на пункт, чтобы открыть настройку."),
 "onb_permission_granted": ("On", "Yoqilgan", "Включено"),
 "onb_permission_optional": ("Recommended", "Tavsiya etiladi", "Рекомендуется"),
 "onb_permissions_missing": ("Without the first three, your alarm may ring late or not show over the lock screen.", "Dastlabki uchtasisiz budilnik kechikishi yoki qulf ekranida chiqmasligi mumkin.", "Без первых трёх будильник может запоздать или не появиться на экране блокировки."),
 "onb_first_alarm_title": ("Set your first alarm", "Birinchi budilnikni qo'ying", "Поставьте первый будильник"),
 "onb_first_alarm_subtitle": ("Pick a time and a mission. You can change both later.", "Vaqt va missiyani tanlang. Keyin o'zgartirishingiz mumkin.", "Выберите время и задание. Потом всё можно изменить."),
 "onb_mission_math_detail": ("Solve one easy sum before the alarm stops.", "Budilnik to'xtashidan oldin bitta oson misol yeching.", "Решите один простой пример, чтобы будильник замолчал."),
 "onb_mission_shake_detail": ("Shake the phone until you're properly awake.", "Rostdan uyg'onguningizcha telefonni silkiting.", "Трясите телефон, пока не проснётесь."),
 "onb_default_label": ("Wake up", "Uyg'oning", "Подъём"),
 "onb_get_started": ("Get started", "Boshlash", "Начать"),
 "onb_set_alarm": ("Set alarm", "Budilnikni qo'yish", "Поставить будильник"),
 "onb_skip": ("Skip for now", "Hozircha o'tkazib yuborish", "Пропустить"),
 "onb_save_failed": ("Couldn't save the alarm: %s", "Budilnikni saqlab bo'lmadi: %s", "Не удалось сохранить будильник: %s"),
 "premium": ("Premium", "Premium", "Premium"),
 "pw_title": ("Every morning, yours", "Har bir tong — sizniki", "Каждое утро — ваше"),
 "pw_subtitle": ("Unlock every mission, every alarm and your full sleep history.", "Barcha missiyalar, cheksiz budilnik va to'liq uyqu tarixi.", "Все задания, все будильники и полная история сна."),
 "pw_reason_alarms": ("Free covers two alarms. Premium has no limit.", "Bepul versiyada ikkita budilnik. Premium'da cheklov yo'q.", "Бесплатно — два будильника. В Premium без ограничений."),
 "pw_reason_missions": ("Steps, QR, Memory, Typing, Draw, Jump and Catch the cat are Premium.", "Qadam, QR, Xotira, Yozish, Chizish, Sakrash va Mushukni tut — Premium'da.", "Шаги, QR, Память, Набор текста, Рисунок, Прыжки и «Поймай кота» — в Premium."),
 "pw_reason_sleep": ("Last night is free. Your full history and trend are Premium.", "Kechagi tun bepul. To'liq tarix va o'zgarish grafigi Premium'da.", "Прошлая ночь бесплатно. Вся история и тренд — в Premium."),
 "pw_reason_widget": ("The Streak and Sleep widgets are Premium.", "Seriya va Uyqu vidjetlari Premium'da.", "Виджеты серии и сна — в Premium."),
 "pw_reason_naps": ("Today's three Cat Naps are free. Unlimited puzzles, past days and hints are Premium.", "Bugungi uchta Cat Naps bepul. Cheksiz boshqotirmalar, o'tgan kunlar va maslahatlar Premium'da.", "Три сегодняшних Cat Naps бесплатно. Безлимит, прошлые дни и подсказки — в Premium."),
 "pw_reason_naps_unlimited": ("Want another? Premium makes a new Cat Naps board every time.", "Yana bittami? Premium har safar yangi Cat Naps taxtasini yaratadi.", "Ещё одну? Premium каждый раз создаёт новую доску Cat Naps."),
 "pw_benefit_alarms": ("Unlimited alarms and all 9 missions", "Cheksiz budilnik va barcha 9 missiya", "Безлимитные будильники и все 9 заданий"),
 "pw_benefit_sleep": ("Sleep history and your 30-day trend", "Uyqu tarixi va 30 kunlik o'zgarish", "История сна и тренд за 30 дней"),
 "pw_benefit_widgets": ("Streak and Sleep widgets", "Seriya va Uyqu vidjetlari", "Виджеты серии и сна"),
 "pw_benefit_naps": ("Unlimited Cat Naps puzzles, every past day, and hints", "Cheksiz Cat Naps, o'tgan kunlar va maslahatlar", "Безлимитные Cat Naps, прошлые дни и подсказки"),
 "pw_benefit_wake_check": ("Wake checks so you don't drift back to sleep", "Yana uxlab qolmaslik uchun uyg'oqlik tekshiruvi", "Проверка пробуждения, чтобы снова не уснуть"),
 "pw_loading": ("Loading plans…", "Tariflar yuklanmoqda…", "Загрузка тарифов…"),
 "pw_unavailable": ("Plans couldn't be loaded", "Tariflarni yuklab bo'lmadi", "Не удалось загрузить тарифы"),
 "pw_unavailable_detail": ("Check your connection and try again.", "Internetni tekshirib, qayta urinib ko'ring.", "Проверьте соединение и попробуйте снова."),
 "pw_store_missing": ("The store isn't set up in this build yet.", "Bu versiyada do'kon hali sozlanmagan.", "В этой сборке магазин ещё не настроен."),
 "pw_try_again": ("Try again", "Qayta urinish", "Повторить"),
 "pw_annual": ("Annual", "Yillik", "Годовой"),
 "pw_monthly": ("Monthly", "Oylik", "Месячный"),
 "pw_annual_detail": ("%1$s per year · %2$s a month", "Yiliga %1$s · oyiga %2$s", "%1$s в год · %2$s в месяц"),
 "pw_annual_detail_plain": ("%s per year", "Yiliga %s", "%s в год"),
 "pw_monthly_detail": ("%s per month · cancel any time", "Oyiga %s · istalgan vaqt bekor qilinadi", "%s в месяц · отмена в любой момент"),
 "pw_trial_badge": ("%d DAYS FREE", "%d KUN BEPUL", "%d ДНЕЙ БЕСПЛАТНО"),
 "pw_start_trial": ("Start %d-day free trial", "%d kunlik bepul sinovni boshlash", "Начать бесплатный период на %d дн."),
 "pw_subscribe": ("Subscribe", "Obuna bo'lish", "Оформить подписку"),
 "pw_terms": ("Dawnwick Premium renews automatically at %1$s per %2$s until you cancel. Cancel any time in Google Play › Payments & subscriptions.", "Dawnwick Premium bekor qilmaguningizcha har %2$s %1$s narxda avtomatik yangilanadi. Google Play › To'lovlar va obunalar bo'limida istalgan vaqt bekor qiling.", "Dawnwick Premium продлевается автоматически за %1$s в %2$s, пока вы не отмените. Отменить можно в Google Play › Платежи и подписки."),
 "pw_terms_trial": ("The first %1$d days are free. After that Dawnwick Premium renews automatically at %2$s per %3$s until you cancel. Cancel any time in Google Play › Payments & subscriptions.", "Dastlabki %1$d kun bepul. Keyin bekor qilmaguningizcha har %3$s %2$s narxda avtomatik yangilanadi. Google Play › To'lovlar va obunalar bo'limida istalgan vaqt bekor qiling.", "Первые %1$d дн. бесплатно. Затем Dawnwick Premium продлевается автоматически за %2$s в %3$s, пока вы не отмените. Отменить можно в Google Play › Платежи и подписки."),
 "pw_year": ("year", "yil", "год"),
 "pw_month": ("month", "oy", "месяц"),
 "pw_restore": ("Restore", "Tiklash", "Восстановить"),
 "pw_terms_link": ("Terms", "Shartlar", "Условия"),
 "pw_privacy_link": ("Privacy", "Maxfiylik", "Конфиденциальность"),
 "pw_continue_free": ("Continue with Free", "Bepul davom etish", "Продолжить бесплатно"),
 "pw_nothing_to_restore": ("No subscription found to restore.", "Tiklanadigan obuna topilmadi.", "Подписка для восстановления не найдена."),
 "pw_failed": ("Purchase failed: %s", "Xarid amalga oshmadi: %s", "Покупка не удалась: %s"),
 "pw_welcome": ("Welcome to Premium!", "Premium'ga xush kelibsiz!", "Добро пожаловать в Premium!"),
 "settings_premium_active": ("Premium is on", "Premium yoqilgan", "Premium активен"),
 "settings_premium_renews": ("Renews or ends %s", "%s da yangilanadi yoki tugaydi", "Продлится или закончится %s"),
 "settings_premium_get": ("Get Premium", "Premium olish", "Получить Premium"),
 "settings_manage_subscription": ("Manage subscription", "Obunani boshqarish", "Управление подпиской"),
 "premium_mission_locked": ("This mission is Premium.", "Bu missiya Premium'da.", "Это задание доступно в Premium."),
 "widget_next_alarm": ("Next Alarm", "Keyingi budilnik", "Следующий будильник"),
 "widget_next_alarm_desc": ("Your next alarm and the missions that turn it off.", "Keyingi budilnik va uni o'chiradigan missiyalar.", "Ближайший будильник и задания, которые его выключат."),
 "widget_cat": ("Cat", "Mushuk", "Кот"),
 "widget_cat_desc": ("The cat sleeps when you do and celebrates your mornings.", "Mushuk siz bilan uxlaydi va tonglaringizni nishonlaydi.", "Кот спит вместе с вами и радуется вашим утрам."),
 "widget_streak": ("Streak", "Seriya", "Серия"),
 "widget_streak_desc": ("Your streak and this week, one paw per morning.", "Seriyangiz va shu hafta — har tongga bitta panja.", "Ваша серия и эта неделя — по лапке за утро."),
 "widget_sleep": ("Sleep", "Uyqu", "Сон"),
 "widget_sleep_desc": ("Last night and the week's nights.", "Kechagi tun va haftaning tunlari.", "Прошлая ночь и ночи этой недели."),
 "widget_tap_to_set": ("Tap to set one.", "Qo'yish uchun bosing.", "Нажмите, чтобы поставить."),
 "widget_cat_asleep_until": ("Asleep. Up at %s.", "Uxlayapti. %s da turadi.", "Спит. Встанет в %s."),
 "widget_cat_asleep": ("Asleep.", "Uxlayapti.", "Спит."),
 "widget_cat_won_day": ("Morning won. Day %d.", "Tong yutildi. %d-kun.", "Утро за вами. День %d."),
 "widget_cat_won": ("Morning won.", "Tong yutildi.", "Утро за вами."),
 "widget_cat_missed": ("Missed one. Tomorrow counts.", "Bittasi o'tkazib yuborildi. Ertaga hisoblanadi.", "Одно утро пропущено. Завтра считается."),
 "widget_cat_ready": ("Ready for tonight.", "Bu kechaga tayyor.", "Готов к ночи."),
 "widget_cat_no_alarm": ("No alarm yet.", "Hali budilnik yo'q.", "Будильника пока нет."),
 "widget_days_in_row": ("%d days in a row", "Ketma-ket %d kun", "%d дн. подряд"),
 "widget_best": ("Best %d", "Eng yaxshi: %d", "Лучшая: %d"),
 "widget_average": ("Average %s", "O'rtacha %s", "В среднем %s"),
 "widget_last_night": ("Last night", "Kechagi tun", "Прошлая ночь"),
 "widget_no_nights": ("No nights yet", "Hali tunlar yo'q", "Ночей пока нет"),
 "widget_locked": ("Premium widget. Tap to unlock.", "Premium vidjet. Ochish uchun bosing.", "Виджет Premium. Нажмите, чтобы открыть."),
 "widget_hours_minutes": ("%1$dh %2$dm", "%1$d soat %2$d daq", "%1$d ч %2$d мин"),
 "app_icon": ("App icon", "Ilova belgisi", "Значок приложения"),
 "app_icon_footer": ("The cat on your home screen, in the mood that suits you.", "Bosh ekrandagi mushuk — kayfiyatingizga mosi.", "Кот на главном экране — в подходящем вам настроении."),
 "app_icon_classic": ("Classic", "Klassik", "Классика"),
 "app_icon_night": ("Night", "Tun", "Ночь"),
 "app_icon_proud": ("Proud", "Mag'rur", "Гордый"),
 "app_icon_startled": ("Startled", "Cho'chigan", "Испуганный"),
 "app_icon_unimpressed": ("Unimpressed", "Befarq", "Невпечатлённый"),
 "app_icon_failed": ("The icon couldn't be changed.", "Belgini o'zgartirib bo'lmadi.", "Не удалось сменить значок."),
 "app_icon_note": ("Your launcher may take a moment to show the new icon.", "Yangi belgi bosh ekranda biroz vaqtdan keyin ko'rinishi mumkin.", "Новый значок может появиться не сразу."),
 "restore_purchases": ("Restore purchases", "Xaridlarni tiklash", "Восстановить покупки"),
 "terms_of_use": ("Terms of use", "Foydalanish shartlari", "Условия использования"),
 "connections": ("Connections", "Ulanishlar", "Подключения"),
 "health_connect": ("Health Connect", "Health Connect", "Health Connect"),
 "connected": ("Connected", "Ulangan", "Подключено"),
 "not_connected": ("Not connected", "Ulanmagan", "Не подключено"),
 "pw_benefit_icons": ("Four more app icons", "Yana to'rtta ilova belgisi", "Ещё четыре значка приложения"),
 "pw_free_includes": ("Free includes %d alarms with the Math and Shake missions.", "Bepul versiyada Matematika va Silkitish missiyalari bilan %d ta budilnik.", "Бесплатно — %d будильника с заданиями «Математика» и «Встряхнуть»."),
 "onb_step_of": ("Step %1$d of %2$d", "%1$d-qadam / %2$d", "Шаг %1$d из %2$d"),
 "onb_wake_time": ("Wake time", "Uyg'onish vaqti", "Время подъёма"),
 "onb_how_turn_off": ("How you'll turn it off", "Qanday o'chirasiz", "Как вы его выключите"),
 "pets_title": ("Companion", "Hamroh", "Компаньон"),
 "pets_footer": ("Your companion is with you on Today, at the alarm, in Sleep and on the widgets, and its call is the alarm's “Meow” sound. The games stay the cat's.", "Hamrohingiz Bugun sahifasida, budilnikda, Uyquda va vidjetlarda siz bilan bo'ladi, uning ovozi esa budilnikning “Miyov” ohangi bo'ladi. O'yinlar mushukniki bo'lib qoladi.", "Компаньон с вами на экране «Сегодня», в будильнике, во сне и на виджетах, а его голос звучит вместо «Мяу» в будильнике. Игры остаются за котом."),
 "pet_cat": ("Cat", "Mushuk", "Кот"),
 "pet_puppy": ("Puppy", "Kuchukcha", "Щенок"),
 "pet_chick": ("Chick", "Jo'jacha", "Цыплёнок"),
 "pet_canary": ("Canary", "Kanareyka", "Канарейка"),
 "pet_lamb": ("Lamb", "Qo'zichoq", "Ягнёнок"),
 "pet_owl": ("Owlet", "Boyo'g'licha", "Совёнок"),
 "pet_hamster": ("Hamster", "Hamyak", "Хомяк"),
 "pet_chosen": ("Chosen", "Tanlangan", "Выбран"),
 "pet_choose": ("Choose", "Tanlash", "Выбрать"),
 "pet_tap_to_hear": ("Hear its voice", "Ovozini eshitish", "Послушать голос"),
 "pet_unlock_streak": ("Wake up %d mornings in a row to unlock", "Ochish uchun ketma-ket %d tong turing", "Вставайте %d утр подряд, чтобы открыть"),
 "pet_unlock_nights": ("Track your sleep for %d nights to unlock", "Ochish uchun %d kecha uyqungizni kuzating", "Отслеживайте сон %d ночей, чтобы открыть"),
 "pet_buy": ("Buy · %s", "Sotib olish · %s", "Купить · %s"),
 "pet_or_premium": ("Or get every companion with Premium", "Yoki Premium bilan barcha hamrohlarni oling", "Или все компаньоны с Premium"),
 "pet_store_unavailable": ("The store isn't set up in this build yet.", "Bu versiyada do'kon hali sozlanmagan.", "В этой сборке магазин ещё не настроен."),
 "pet_unlocked": ("%s is yours!", "%s endi sizniki!", "%s — теперь с вами!"),
 "voice_cat": ("Meow", "Miyov", "Мяу"),
 "voice_puppy": ("Woof", "Vov", "Гав"),
 "voice_chick": ("Cock-a-doodle-doo", "Qu-qu-qu", "Кукареку"),
 "voice_canary": ("Birdsong", "Sayrash", "Пение"),
 "voice_lamb": ("Baa", "Ma-a", "Бе-е"),
 "voice_owl": ("Hoot", "Uhu", "Уху"),
 "voice_hamster": ("Squeak", "Chiy-chiy", "Писк"),
 "voice_detail_companion": ("Your companion, wanting you up", "Hamrohingiz turishingizni istayapti", "Компаньон, который хочет, чтобы вы встали"),
 "pw_reason_companions": ("Premium opens every companion. Or buy the one you like on its own.", "Premium barcha hamrohlarni ochadi. Yoki yoqqanini alohida sotib oling.", "Premium открывает всех компаньонов. Или купите понравившегося отдельно."),
 "pw_benefit_companions": ("Six more companions, each with its own voice", "Har biri o'z ovoziga ega yana 6 ta hamroh", "Ещё шесть компаньонов, у каждого свой голос"),
 "tricks_title_pet": ("Your companion's tricks", "Hamrohingizning hiylalari", "Трюки компаньона"),
 "tricks_detail_pet": ("A streak teaches your companion a trick at 3, 7, 14, 30, 60 and 100 mornings. It keeps them, whatever happens to the streak.", "Seriya hamrohingizga 3, 7, 14, 30, 60 va 100 tongda hiyla o'rgatadi. Seriya uzilsa ham ular qoladi.", "Серия учит компаньона трюку на 3, 7, 14, 30, 60 и 100 утрах. Они остаются, что бы ни случилось с серией."),
 "trick_wave_detail_pet": ("Tap your companion and it waves back.", "Hamrohingizni bosing — u qo'l silkitadi.", "Нажмите на компаньона — он помашет в ответ."),
 "trick_collar_detail_pet": ("A collar with a yolk bell, everywhere your companion goes.", "Hamrohingiz qayerga borsa, sariq qo'ng'iroqli bo'yinbog' bilan.", "Ошейник с жёлтым колокольчиком, куда бы ни пошёл компаньон."),
 "covers_ready_title_pet": ("Your companion has your back", "Hamrohingiz sizni qo'llab-quvvatlaydi", "Компаньон вас прикроет"),
 "wind_down_detail_pet": ("Breathe with your companion for a few minutes: in for four, out for six. A soft tap marks each turn, so you can close your eyes.", "Bir necha daqiqa hamrohingiz bilan nafas oling: to'rt soniya ichga, olti soniya tashqariga. Har burilishda yengil titrash bo'ladi, ko'zingizni yumishingiz mumkin.", "Подышите с компаньоном несколько минут: вдох на четыре, выдох на шесть. Лёгкий толчок отмечает каждую смену — можно закрыть глаза."),
}

ARRAYS = {
 "weekday_letter": (["S", "M", "T", "W", "T", "F", "S"], ["Ya", "Du", "Se", "Ch", "Pa", "Ju", "Sh"], ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"]),
 "weekday_short": (["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"], ["Yak", "Dush", "Sesh", "Chor", "Pay", "Jum", "Shan"], ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"]),
 "weekday_long": (["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                  ["Yakshanba", "Dushanba", "Seshanba", "Chorshanba", "Payshanba", "Juma", "Shanba"],
                  ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"]),
 "difficulty": (["Easy", "Medium", "Hard"], ["Oson", "O'rtacha", "Qiyin"], ["Легко", "Средне", "Сложно"]),
 "sound_names": (["Default", "Gentle", "Rise", "Pulse", "Chime", "Digital", "Meow"],
                 ["Standart", "Mayin", "Ko'tariluvchi", "Puls", "Qo'ng'iroq", "Raqamli", "Miyov"],
                 ["Стандартный", "Мягкий", "Нарастающий", "Пульс", "Колокол", "Цифровой", "Мяу"]),
 "sound_details": (["Classic two-beep", "Soft bell chime", "Escalating tones", "Deep rhythm", "Warm bell tone", "Classic digital beep", "The cat, wanting you up"],
                   ["Klassik ikki signal", "Mayin qo'ng'iroq", "Kuchayib boruvchi ohang", "Chuqur ritm", "Iliq qo'ng'iroq", "Klassik raqamli signal", "Turishingizni istagan mushuk"],
                   ["Классический двойной сигнал", "Мягкий звон", "Нарастающие тона", "Глубокий ритм", "Тёплый колокол", "Цифровой сигнал", "Кот, который хочет, чтобы вы встали"]),
 "gradual_names": (["Off", "15 sec", "30 sec", "60 sec", "3 min"], ["O'chiq", "15 soniya", "30 soniya", "60 soniya", "3 daqiqa"], ["Выкл.", "15 сек", "30 сек", "60 сек", "3 мин"]),
}

PLURALS = {  # en (one, other) · uz other · ru (one, few, many)
 "rounds": (("%d round", "%d rounds"), "%d raund", ("%d раунд", "%d раунда", "%d раундов")),
 "shakes": (("%d shake", "%d shakes"), "%d silkitish", ("%d встряхивание", "%d встряхивания", "%d встряхиваний")),
 "steps": (("%d step", "%d steps"), "%d qadam", ("%d шаг", "%d шага", "%d шагов")),
 "jumps": (("%d jump", "%d jumps"), "%d sakrash", ("%d прыжок", "%d прыжка", "%d прыжков")),
 "noise_events": (("%d noise event", "%d noise events"), "%d ta shovqin", ("%d шум", "%d шума", "%d шумов")),
 "points": (("%d point", "%d points"), "%d ochko", ("%d очко", "%d очка", "%d очков")),
 "days_in_a_row": (("%d day in a row", "%d days in a row"), "ketma-ket %d kun", ("%d день подряд", "%d дня подряд", "%d дней подряд")),
 "pet_mornings_progress": (("%1$d of %2$d morning", "%1$d of %2$d mornings"), "%1$d / %2$d tong", ("%1$d из %2$d утра", "%1$d из %2$d утр", "%1$d из %2$d утр")),
 "pet_nights_progress": (("%1$d of %2$d night", "%1$d of %2$d nights"), "%1$d / %2$d kecha", ("%1$d из %2$d ночи", "%1$d из %2$d ночей", "%1$d из %2$d ночей")),
 "sleep_earlier_nights_locked": (("%d earlier night — see it with Premium", "%d earlier nights — see them with Premium"), "Yana %d ta oldingi tun — Premium bilan ko'ring", ("Ещё %d ночь — смотрите в Premium", "Ещё %d ночи — смотрите в Premium", "Ещё %d ночей — смотрите в Premium")),
}


def text(s):
    s = escape(s).replace("'", "\\'").replace('"', '\\"')
    return s


def write(folder, idx):
    out = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by tools/strings.py. Edit there. -->", "<resources>"]
    for k, v in S.items():
        # The brand name stays as it is in every language.
        attr = ' translatable="false"' if k == "app_name" else ""
        if k == "app_name" and idx:
            continue
        out.append(f'    <string name="{k}"{attr}>{text(v[idx])}</string>')
    for k, v in ARRAYS.items():
        out.append(f'    <string-array name="{k}">')
        out += [f"        <item>{text(i)}</item>" for i in v[idx]]
        out.append("    </string-array>")
    for k, (en, uz, ru) in PLURALS.items():
        out.append(f'    <plurals name="{k}">')
        if idx == 0:
            out += [f'        <item quantity="one">{text(en[0])}</item>', f'        <item quantity="other">{text(en[1])}</item>']
        elif idx == 1:
            out += [f'        <item quantity="one">{text(uz)}</item>', f'        <item quantity="other">{text(uz)}</item>']
        else:
            out += [f'        <item quantity="one">{text(ru[0])}</item>', f'        <item quantity="few">{text(ru[1])}</item>',
                    f'        <item quantity="many">{text(ru[2])}</item>', f'        <item quantity="other">{text(ru[1])}</item>']
        out.append("    </plurals>")
    out.append("</resources>")
    d = RES / folder
    d.mkdir(parents=True, exist_ok=True)
    (d / "strings.xml").write_text("\n".join(out) + "\n")


for i, folder in enumerate(["values", "values-uz", "values-ru"]):
    write(folder, i)
print(len(S), "strings,", len(ARRAYS), "arrays,", len(PLURALS), "plurals")

# The iOS app's other ten languages, one JSON file each in tools/translations/.
# Add or fix a string there and run this again; a key missing there falls back to English.
LANGS = {"de": "de", "es": "es", "fr": "fr", "it": "it", "ja": "ja", "ko": "ko", "pt-BR": "pt-rBR",
         "tr": "tr", "zh-Hans": "b+zh+Hans", "zh-Hant": "b+zh+Hant"}
MANY = {"es", "fr", "it", "pt-BR"}  # CLDR gives these a "many" form for very large numbers


def write_translation(lang, qualifier):
    t = json.loads((pathlib.Path(__file__).resolve().parent / "translations" / f"{lang}.json").read_text(encoding="utf-8"))
    out = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by tools/strings.py from tools/translations. Edit there. -->", "<resources>"]
    missing = [k for k in S if k != "app_name" and k not in t["strings"]]
    for k, v in S.items():
        if k == "app_name":
            continue
        out.append(f'    <string name="{k}">{text(t["strings"].get(k, v[0]))}</string>')
    for k, v in ARRAYS.items():
        items = t["arrays"].get(k, v[0])
        out.append(f'    <string-array name="{k}">')
        out += [f"        <item>{text(i)}</item>" for i in items]
        out.append("    </string-array>")
    for k, v in PLURALS.items():
        forms = t["plurals"].get(k, {"one": v[0][0], "other": v[0][1]})
        if lang in MANY and "one" in forms:
            forms = {**forms, "many": forms["other"]}
        out.append(f'    <plurals name="{k}">')
        out += [f'        <item quantity="{q}">{text(x)}</item>' for q, x in forms.items()]
        out.append("    </plurals>")
    out.append("</resources>")
    d = RES / f"values-{qualifier}"
    d.mkdir(parents=True, exist_ok=True)
    (d / "strings.xml").write_text("\n".join(out) + "\n")
    if missing:
        print(f"  {lang}: {len(missing)} strings fall back to English: {', '.join(missing[:8])}")


for lang, qualifier in LANGS.items():
    write_translation(lang, qualifier)
print(len(LANGS), "more languages from tools/translations")
