// Generated by tools/strings.py from tools/pets.py. Edit there.
package uz.ata.dawnwick.ui.games

import uz.ata.dawnwick.R
import uz.ata.dawnwick.companion.Pet

/** The games' words that name the cat, and each companion's version of them. */
object PetStrings {
    private val table: Map<Int, Map<Pet, Int>> = mapOf(
        R.string.game_catch to mapOf(Pet.PUPPY to R.string.game_catch_puppy, Pet.CHICK to R.string.game_catch_chick, Pet.CANARY to R.string.game_catch_canary, Pet.LAMB to R.string.game_catch_lamb, Pet.OWL to R.string.game_catch_owl, Pet.HAMSTER to R.string.game_catch_hamster),
        R.string.game_naps to mapOf(Pet.PUPPY to R.string.game_naps_puppy, Pet.CHICK to R.string.game_naps_chick, Pet.CANARY to R.string.game_naps_canary, Pet.LAMB to R.string.game_naps_lamb, Pet.OWL to R.string.game_naps_owl, Pet.HAMSTER to R.string.game_naps_hamster),
        R.string.catch_hint to mapOf(Pet.PUPPY to R.string.catch_hint_puppy, Pet.CHICK to R.string.catch_hint_chick, Pet.CANARY to R.string.catch_hint_canary, Pet.LAMB to R.string.catch_hint_lamb, Pet.OWL to R.string.catch_hint_owl, Pet.HAMSTER to R.string.catch_hint_hamster),
        R.string.boxes_watch to mapOf(Pet.PUPPY to R.string.boxes_watch_puppy, Pet.CHICK to R.string.boxes_watch_chick, Pet.CANARY to R.string.boxes_watch_canary, Pet.LAMB to R.string.boxes_watch_lamb, Pet.OWL to R.string.boxes_watch_owl, Pet.HAMSTER to R.string.boxes_watch_hamster),
        R.string.detail_boxes to mapOf(Pet.PUPPY to R.string.detail_boxes_puppy, Pet.CHICK to R.string.detail_boxes_chick, Pet.CANARY to R.string.detail_boxes_canary, Pet.LAMB to R.string.detail_boxes_lamb, Pet.OWL to R.string.detail_boxes_owl, Pet.HAMSTER to R.string.detail_boxes_hamster),
        R.string.detail_boxes_best to mapOf(Pet.PUPPY to R.string.detail_boxes_best_puppy, Pet.CHICK to R.string.detail_boxes_best_chick, Pet.CANARY to R.string.detail_boxes_best_canary, Pet.LAMB to R.string.detail_boxes_best_lamb, Pet.OWL to R.string.detail_boxes_best_owl, Pet.HAMSTER to R.string.detail_boxes_best_hamster),
        R.string.naps_count to mapOf(Pet.PUPPY to R.string.naps_count_puppy, Pet.CHICK to R.string.naps_count_chick, Pet.CANARY to R.string.naps_count_canary, Pet.LAMB to R.string.naps_count_lamb, Pet.OWL to R.string.naps_count_owl, Pet.HAMSTER to R.string.naps_count_hamster),
        R.string.naps_share_text to mapOf(Pet.PUPPY to R.string.naps_share_text_puppy, Pet.CHICK to R.string.naps_share_text_chick, Pet.CANARY to R.string.naps_share_text_canary, Pet.LAMB to R.string.naps_share_text_lamb, Pet.OWL to R.string.naps_share_text_owl, Pet.HAMSTER to R.string.naps_share_text_hamster),
        R.string.boxes_rules to mapOf(Pet.PUPPY to R.string.boxes_rules_puppy, Pet.CHICK to R.string.boxes_rules_chick, Pet.CANARY to R.string.boxes_rules_canary, Pet.LAMB to R.string.boxes_rules_lamb, Pet.OWL to R.string.boxes_rules_owl, Pet.HAMSTER to R.string.boxes_rules_hamster),
        R.string.catch_rules to mapOf(Pet.PUPPY to R.string.catch_rules_puppy, Pet.CHICK to R.string.catch_rules_chick, Pet.CANARY to R.string.catch_rules_canary, Pet.LAMB to R.string.catch_rules_lamb, Pet.OWL to R.string.catch_rules_owl, Pet.HAMSTER to R.string.catch_rules_hamster),
        R.string.laser_rules to mapOf(Pet.PUPPY to R.string.laser_rules_puppy, Pet.CHICK to R.string.laser_rules_chick, Pet.CANARY to R.string.laser_rules_canary, Pet.LAMB to R.string.laser_rules_lamb, Pet.OWL to R.string.laser_rules_owl, Pet.HAMSTER to R.string.laser_rules_hamster),
        R.string.naps_rules to mapOf(Pet.PUPPY to R.string.naps_rules_puppy, Pet.CHICK to R.string.naps_rules_chick, Pet.CANARY to R.string.naps_rules_canary, Pet.LAMB to R.string.naps_rules_lamb, Pet.OWL to R.string.naps_rules_owl, Pet.HAMSTER to R.string.naps_rules_hamster),
    )

    /** `id` as `pet` would have it: the cat's own words when there is no other version. */
    fun of(id: Int, pet: Pet): Int = table[id]?.get(pet) ?: id
}
